### ISSUE TITLE
Put jenkinsflow to pypi

### ISSUE THREAD

**Issue by lechat** [lhupfeldt/jenkinsflow#15]
It would be nice if jenkinsflow would be available in https://pypi.python.org

**Comment by lhupfeldt** [comment]
Is now on pypi

**Comment by lechat** [comment]
Hi Lars,

The install from pypi fails:

```
/home/aleksey/src/environments/scripts/pex/vvv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached jenkinsflow-1.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9WpMpn/jenkinsflow/setup.py", line 68, in <module>
        ''',
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/aleksey/src/environments/scripts/pex/vvv/lib/python2.7/site-packages/setuptools/dist.py", line 260, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/home/aleksey/src/environments/scripts/pex/vvv/lib/python2.7/site-packages/setuptools/dist.py", line 285, in fetch_build_eggs
        replace_conflicting=True
      File "/home/aleksey/src/environments/scripts/pex/vvv/lib/python2.7/site-packages/pkg_resources.py", line 603, in resolve
        requirements = list(requirements)[::-1]
      File "/home/aleksey/src/environments/scripts/pex/vvv/lib/python2.7/site-packages/pkg_resources.py", line 2678, in parse_requirements
        "version spec")
      File "/home/aleksey/src/environments/scripts/pex/vvv/lib/python2.7/site-packages/pkg_resources.py", line 2645, in scan_list
        raise ValueError(msg, line, "at", line[p:])
    ValueError: ('Expected version spec in', 'setuptools-version-command~=2.2', 'at', '~=2.2')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9WpMpn/jenkinsflow
```

**Comment by lhupfeldt** [comment]
Hi Aleksey,

I can't reproduce.
Judging from the stack trace it seems there are two issues:

1) The InsecurePlatformWarning suggests that there is something wrong with the SSL setup on your platform. Which OS/version are you on? Which ssl packages have you got installed?
2) ValueError: ('Expected version spec in', 'setuptools-version-command~=2.2', 'at', '~=2.2') means that you are using an old version of setuptools/pip which does not support ~ style version specifications. What versions of setuptools/pip are you using? Can you update them?

Is this failing with both Python 2 and 3?

**Comment by lechat** [comment]
It is failing on python 2.7. I use latest pip, upgraded it when had this problem first time - same result. Perhaps I need to upgrade setuptools... 

InsecurePlatformWarning is just a warning from `requests`, doesn't affect anything. 

I am in Fedora 20.

**Comment by lhupfeldt** [comment]
The dependency version patterns follow pep 440, which was accepted Aug 2014. I don't know when it was implemented in distutils or which patterns were accepted before that. I guess your version of disutils (Python) is too old.

**Comment by lhupfeldt** [comment]
I have:
```
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import distutils
>>> print distutils.__version__
2.7.10
```

**Comment by lhupfeldt** [comment]
Please try changing one of the dependencies to not use ~, e.g.:

```
        install_requires=['requests~=2.7.0', ...
```
to
```
        install_requires=['requests>=2.7.0,==2.*', ...
```
This should have the same meaning. I'm hoping this is understood by your version of distutils.

**Comment by lhupfeldt** [comment]
Did you try to change the pattern?

**Comment by lhupfeldt** [comment]
Did you try to change the pattern?

**Comment by lechat** [comment]
No, I haven't changed pattern, but upgraded to latest version both pip and setuptools. Upgrading setuptools solved that problem.

**Comment by lhupfeldt** [comment]
Ok
